-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5645_PRE_COMM" (
 "ORDER_LINE" CHAR(12),
 "ORDER_NO" CHAR(7),
 "LINE_NO" CHAR(4),
 "IDENTIFIER" CHAR(4),
 "SALESPERSON" CHAR(3),
 "RATE" NUMERIC(6,4) DEFAULT '0.0',
 "COMM_TOTAL" NUMERIC(8,2) DEFAULT '0.0',
 "GSS_USER" CHAR(9),
 "LAST_DATE" CHAR(10),
 "INVOICED" CHAR(1) DEFAULT 'N',
 "CREDIT_MEMO" CHAR(1) DEFAULT 'N' );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
