-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5645_COMMISSIONS" (
 "ORDER_LINE" CHAR(12),
 "ORDER_NO" CHAR(7),
 "LINE_NO" CHAR(4),
 "INVOICE" CHAR(7),
 "INVOICE_DATE" CHAR(10),
 "IDENTIFIER" CHAR(4),
 "SALESPERSON" CHAR(3),
 "RATE" NUMERIC(6,4),
 "COMM_TOTAL" NUMERIC(8,2),
 "INV_PAYMENT_DATE" CHAR(10),
 "FLG_INV_PAID" CHAR(10),
 "FLG_COM_PAYABLE" CHAR(1),
 "FLG_COM_2B_PAID" CHAR(10),
 "AP_BATCH" CHAR(5),
 "COMM_BATCH" CHAR(6),
 "FLG_COM_PAID" CHAR(10),
 "GSS_USER" CHAR(9),
 "LAST_DATE" CHAR(10),
 "INVOICE_AMT" NUMERIC(8,2),
 "VENDOR" CHAR(6),
 "PL" CHAR(2) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
