-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5645_OVR_CUST_RT" (
 "CUST_ID" CHAR(6),
 "CUST_RATE" NUMERIC(6,4),
 "GSS_USER" CHAR(9),
 "GSS_DATE" CHAR(10),
 "CUST_SP_ID" CHAR(3) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
